name: Maestro Android Tests

on:
  push:
    branches: [ "master" ]

jobs:
  maestro-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm
          sudo chown $USER /dev/kvm || true

      - name: Run Android emulator and Maestro tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            set -e

            curl -fsSL "https://get.maestro.mobile.dev" | bash
            export PATH="$HOME/.maestro/bin:$PATH"

            adb wait-for-device

            until adb shell getprop sys.boot_completed | grep -m 1 "1"; do
              sleep 2
            done

            adb shell input keyevent 82

            adb install -r apk/ApiDemos-debug.apk

            maestro --version
            maestro test tests/first-test.yaml
